c2_show_bytes: c2_show_bytes.c
	gcc -o c2_show_bytes -pedantic -Wall -Werror -ggdb3 -std=gnu99 c2_show_bytes.c
c2_strlonger: c2_strlonger.c
	gcc -o c2_strlonger -pedantic -Wall -Werror -ggdb3 -std=gnu99 c2_strlonger.c